# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.0  # Use the latest version compatible with Go 1.23
    hooks:
      - id: golangci-lint
        args: [--timeout=5m]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-mod-tidy
      - id: go-build
      - id: go-unit-tests

  - repo: local
    hooks:
      - id: gofumpt
        name: gofumpt
        description: Run gofumpt on Go files
        entry: gofumpt -w
        language: system
        types: [go]
        pass_filenames: true

      - id: goimports-local
        name: goimports with local prefix
        description: Run goimports with local prefix
        entry: goimports -w -local github.com/redis/go-redis
        language: system
        types: [go]
        pass_filenames: true

      - id: custom-vet
        name: Custom vet tool
        description: Run custom Go vet checks
        entry: bash -c 'cd internal/customvet && go build . && cd ../../ && go vet -vettool ./internal/customvet/customvet'
        language: system
        types: [go]
        pass_filenames: false
